/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jade_reconstruct_area_PJNI */

#ifndef _Included_jade_reconstruct_area_PJNI
#define _Included_jade_reconstruct_area_PJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jade_reconstruct_area_PJNI
 * Method:    matrixExp
 * Signature: ([DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_jade_reconstruct_area_PJNI_matrixExp
  (JNIEnv *, jobject, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
